.PHONY: clean
clean:
	# Python
	find . -type f -name "*.pyc" -delete
	find . -type f -name "*.pyo" -delete
	find . -type d -name "__pycache__" -delete
	# Jupyter
	find . -type f -name "*-checkpoint.ipynb" -delete
	find . -type d -name ".ipynb_checkpoints" -delete
